# Generated by Django 6.0.4 on 2026-05-05 04:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(5)])),
                ('delivery_days', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('revisions', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('featured_image', models.ImageField(upload_to='gigs/featured/')),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL')),
                ('requirements', models.JSONField(blank=True, default=list, help_text='List of questions for buyer')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('tags', models.CharField(blank=True, help_text='Comma separated tags', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('active', 'Active'), ('paused', 'Paused'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='gigs.category')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-rating', 'price'],
            },
        ),
        migrations.CreateModel(
            name='GigFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='gigs.gig')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GigPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('revisions', models.IntegerField(default=1)),
                ('features', models.TextField(help_text='Line separated features')),
                ('is_active', models.BooleanField(default=True)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='gigs.gig')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='GigRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('text', 'Text Answer'), ('textarea', 'Long Text'), ('file', 'File Upload'), ('checkbox', 'Checkbox'), ('dropdown', 'Dropdown')], default='text', max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, default=list, help_text='For dropdown options')),
                ('order', models.IntegerField(default=0)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_items', to='gigs.gig')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='gigs.category')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='gig',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gigs.subcategory'),
        ),
        migrations.CreateModel(
            name='SavedGig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='gigs.gig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_gigs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'gig')},
            },
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['status', '-created_at'], name='gigs_gig_status_2b8669_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['category', 'status'], name='gigs_gig_categor_c05672_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['freelancer', 'status'], name='gigs_gig_freelan_7e04f8_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['slug'], name='gigs_gig_slug_6216be_idx'),
        ),
    ]
