# Generated by Django 6.0.4 on 2026-05-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('active', 'Active'), ('paused', 'Paused'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
    ]
